### ISSUE TITLE
The result of retraining is not good

### ISSUE THREAD

**Issue by JaosonMa** [lukas-blecher/LaTeX-OCR#147] opened 2022-05-12 02:10 UTC
I clone the project , changed nothing. except change the train&val.pkl path in the config file , use your images retrain.
but i think my result is not good . i check the data , found nothing . 
here is my trian PS img;
![XVM_9A6MKXS0I6KP(S88VS9](https://user-images.githubusercontent.com/23551774/167977727-2da2f2fb-d431-425c-81c5-45d6e4121c5b.png)

i don't know how to check and find the problem

**Comment by lukas-blecher** [comment] 2022-05-12 10:20
Something is wrong here. And I'm not sure what. 
From what you described, everything was correct.
What happens if you run the available pretrained model (download via `python pix2tex.model.checkpoints.get_latest_checkpoint.py`) on the data:
```bash
python pix2tex/eval.py -d path/to/train.pkl
```
If there is a bleu score < 0.8 the data is probably not matched up.

-----
@TITC you trained more models than me by now. Any ideas?

**Comment by TITC** [comment] 2022-05-13 02:09
I'm trying to reproduce the phenomenon 100%, a more helpful reply may come later.

---
Sorry for late response, I pulled the latest code, create a clean conda env last night and do reproduce one time the abnormal bleu score.

![image](https://user-images.githubusercontent.com/35098797/168196228-957c813d-d5a0-4820-b530-d5460335921e.png)

nothing changed but batchsize form 10 to 40, and its turn out normally. I not sure the the reson behind it but maybe pull last version code  or change batchsize could help @JaosonMa.

![image](https://user-images.githubusercontent.com/35098797/168196409-58afa446-dfad-448b-9ad5-d6662d789481.png)




---
This problem never noticed in previous version. Here are some training record one weeks ago. I trained on the dataset provided by Lukas, both print and handwritten, with the same config except random seed. 

[train loss figure](https://wandb.ai/yht4work/LaTeX-OCR-pix2tex/reports/Shared-panel-22-05-12-19-05-98--VmlldzoxOTk0NjM5?accessToken=q36y8uyoye6fzaz33lw0o6esphrlsxh1u8i8com152pz5qod4rrvgpfalvxb5l1q)
![image](https://user-images.githubusercontent.com/35098797/168064069-1c68396e-1ce4-4a78-9baa-2ffee5fa1fc6.png)

[bleu figure
](https://wandb.ai/yht4work/LaTeX-OCR-pix2tex/reports/Shared-panel-22-05-12-19-05-00--VmlldzoxOTk0Njg5?accessToken=jw4war0nuk10sz51og70ct69u81fdwd6v40r91x1na5am3hsahxcdkgytr1sahq5)![image](https://user-images.githubusercontent.com/35098797/168064353-45b3a6ef-d22c-434a-be48-708c89e9cabf.png)
---

**Comment by JaosonMa** [comment] 2022-05-13 02:20
> not matche
i download your pretrained model , then use this cmd to check.
`CUDA_VISIBLE_DEVICES=0 python eval.py -d /xxx/latexOcr/lukas-data/test.pkl -c /xxx/LaTeX-OCR/pix2tex/checkpoints/pix2tex/weights.pth`
but it is very slow , is it normal?
i think data should be all right.
![wq](https://user-images.githubusercontent.com/23551774/168198493-66e07675-9634-4313-8052-bcf2fa8f0db9.gif)

**Comment by JaosonMa** [comment] 2022-05-13 02:21
> I'm trying to reproduce the phenomenon 100%, a more helpful reply may come later.
> 
> Sorry for late response, I pulled the latest code, create a clean conda env last night and do reproduce one time the abnormal bleu score.
> 
> ![image](https://user-images.githubusercontent.com/35098797/168196228-957c813d-d5a0-4820-b530-d5460335921e.png)
> 
> nothing changed but batchsize form 10 to 40, and its turn out normally. I not sure the the reson behind it but maybe pull last version code or change batchsize could help @JaosonMa.
> 
> ![image](https://user-images.githubusercontent.com/35098797/168196409-58afa446-dfad-448b-9ad5-d6662d789481.png)
> 
> This problem never noticed in previous version. Here are some training record one weeks ago. I trained on the dataset provided by Lukas, both print and handwritten, with the same config except random seed.
> 
> [train loss figure](https://wandb.ai/yht4work/LaTeX-OCR-pix2tex/reports/Shared-panel-22-05-12-19-05-98--VmlldzoxOTk0NjM5?accessToken=q36y8uyoye6fzaz33lw0o6esphrlsxh1u8i8com152pz5qod4rrvgpfalvxb5l1q) ![image](https://user-images.githubusercontent.com/35098797/168064069-1c68396e-1ce4-4a78-9baa-2ffee5fa1fc6.png)
> 
> ## [bleu figure ](https://wandb.ai/yht4work/LaTeX-OCR-pix2tex/reports/Shared-panel-22-05-12-19-05-00--VmlldzoxOTk0Njg5?accessToken=jw4war0nuk10sz51og70ct69u81fdwd6v40r91x1na5am3hsahxcdkgytr1sahq5)![image](https://user-images.githubusercontent.com/35098797/168064353-45b3a6ef-d22c-434a-be48-708c89e9cabf.png)

thanks , i will go to try this ,

**Comment by lukas-blecher** [comment] 2022-05-13 08:12
That's weird. The only thing I changed was to move all transformations into a separate file (see fcb2b09990b78c9a028462a04d96a6aba5792f60)

@TITC which was the last working commit hash? Maybe I missed something. Or did I misunderstand you? Do you say the latest version works, but only for batch size of 40?

@JaosonMa yes, the data looks alright. It's normal that the inference is slower than the training. This is an inherent trait of the transformer architecture. Unlike during training where for one sample only one forwad - backward pass is needed, during inference each token has to be predicted in its own forward pass.

**Comment by JaosonMa** [comment] 2022-05-13 08:56
@TITC @lukas-blecher  Thanks .

I pull the newst code ,and then change batchsize from 10 to 40, but got error, RuntimeError: CUDA out of memory.
then changed batchsize from 40 to 30 ,same error , then from 30 to 20 same error , like the PS img :
my gpu is 12G, so now i can not retrain with your ways @TITC  , 
![image](https://user-images.githubusercontent.com/23551774/168248310-0088bc56-900b-48fa-8944-57435c0ff4e9.png)

**Comment by TITC** [comment] 2022-05-13 09:21
> which was the last working commit hash?

I mean edc40c39804b12c0c52c4507c330c0996a1caefa

> Do you say the latest version works, but only for batch size of 40?

the latest version work with 40, I havn't try other batch size. @lukas-blecher 


---
here are 34 curves in 5 figures. 
- purple:  batch size 40, latest code
- gren: batch size 10, latest code
- origine: batch size 10, latest code
- pink: batch size 10, edc40c39804b12c0c52c4507c330c0996a1caefa

![image](https://user-images.githubusercontent.com/35098797/168252449-36b989c6-804c-4d66-803a-4974fd4af739.png)

---
I think it's may not version problem, just batch size.

> This problem never noticed in previous version. Here are some training record one weeks ago. I trained on the dataset provided by Lukas, both print and handwritten, with the same config except random seed. sorry for misleading.

I recall there do have one time that the model can‘t fit, then I directly changed the batch size to 50 and forgot this matter, and use 50 until now, because the GPU is 3090 has 24GB. 
![image](https://user-images.githubusercontent.com/35098797/168253204-0811d5e7-07eb-46e4-8ff1-61137e486677.png)



>  with the same config except random seed

`the same` config just means their hyper-parameter is same, I do not remember wether the batch size is 10 or 50.

**Comment by lukas-blecher** [comment] 2022-05-13 09:40
Thanks for clarifying.
I think, if it is the batch size and not the random seed, a solution would be to accumulate gradients over multiple micro batches before calling the optimizer step.
I've seen it in the diffusion training and it worked well ([ref](https://github.com/openai/guided-diffusion/blob/27c20a8fab9cb472df5d6bdd6c8d11c8f430b924/guided_diffusion/train_util.py#L180)).
Maybe I'll find the time to implement that today.

**Comment by lukas-blecher** [comment] 2022-05-13 10:39
@JaosonMa can you checkout the [`micro-batch`](https://github.com/lukas-blecher/LaTeX-OCR/tree/micro-batch) branch I just published?
With that you can add a new property to the `config.yaml` called `micro_batchsize`
If it is -1 the normal batch size will be used.
Now you can set `batchsize = 40` and `micro_batchsize = 10`.

**Comment by JaosonMa** [comment] 2022-05-13 10:44
> @JaosonMa can you checkout the [`micro-batch`](https://github.com/lukas-blecher/LaTeX-OCR/tree/micro-batch) branch I just published? With that you can add a new property to the `config.yaml` called `micro_batchsize` If it is -1 the normal batch size will be used. Now you can set `batchsize = 40` and `micro_batchsize = 10`.

ok  , i go to try this right now

**Comment by JaosonMa** [comment] 2022-05-13 11:09
this is what i done :
# git clone -b micro-batch https://github.com/lukas-blecher/LaTeX-OCR.git
# edit the config 
![image](https://user-images.githubusercontent.com/23551774/168270316-a1535524-82d6-40c5-be30-058716184c5d.png)
first set batchsize = 40 , same error as up 
then changed batchsize = 20 , now it is training with no error , i am still looking 
ps:
my GPU have a service is running, it used 1.5G memory, i can not stop this service , i am trying to stop this service , but should one hour later.

**Comment by lukas-blecher** [comment] 2022-05-13 11:15
With the new micro_batchsize, changing the batchsize will not solve this error. You can leave batchsize=40 and try with e.g. micro_batchsize = 8
Each batch will be split into even smaller (micro) batches of size `micro_batchsize`. Only these will be given to the GPU one at a time.

**Comment by TITC** [comment] 2022-05-13 14:13
it's working for me. nice job.
![image](https://user-images.githubusercontent.com/35098797/168302140-758ddd0b-53b3-41ea-bbae-9146db1b204a.png)

**Comment by JaosonMa** [comment] 2022-05-14 00:57
@TITC  how many epoc you traind?
after 10 epoc ,my result is not good enough.
![image](https://user-images.githubusercontent.com/23551774/168404824-3948a8d4-26ef-417b-b8cd-7b99cd45c876.png)

**Comment by TITC** [comment] 2022-05-14 02:08
left downside corner is the `epoch-step` diagram @JaosonMa 

![image](https://user-images.githubusercontent.com/35098797/168406633-3ae0df6e-702e-4976-b79a-a34077a31605.png)


change [`load_chkpt: null` ](https://github.com/lukas-blecher/LaTeX-OCR/blob/e4b102ed30690c3b5488940193d12654cd91418f/pix2tex/model/settings/config.yaml#L26) to `load_chkpt: path to your weight`. (refer the training notebook [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/lukas-blecher/LaTeX-OCR/blob/main/notebooks/LaTeX_OCR_training.ipynb))

**Comment by lukas-blecher** [comment] 2022-05-14 09:23
So the performance does increase now for you too, @JaosonMa. But it's significantly slower than for @TITC 
You can try and continue training as described above.
In the meantime, do you guys have the same hyperparameters, do you maybe want to share the config file? @TITC did you use a random seed this time? Would be nice to know for reproducibility.

**Comment by TITC** [comment] 2022-05-14 09:54
previous experiments about the random seed stuff is a mistake, after https://github.com/lukas-blecher/LaTeX-OCR/discussions/146#discussioncomment-2704466 I never changed random seed. @lukas-blecher 

---
follow the guidance only change these two things.

> Now you can set `batchsize = 40` and `micro_batchsize = 10`.


```yaml
backbone_layers:
- 2
- 3
- 7
betas:
- 0.9
- 0.999
batchsize: 40
bos_token: 1
channels: 1
data: dataset/data/train.pkl
debug: false
decoder_args:
  attn_on_attn: true
  cross_attend: true
  ff_glu: true
  rel_pos_bias: false
  use_scalenorm: false
dim: 256
encoder_depth: 4
eos_token: 2
epochs: 10
gamma: 0.9995
heads: 8
id: null
load_chkpt: null
lr: 0.001
lr_step: 30
max_height: 192
max_seq_len: 512
max_width: 672
micro_batchsize: 10
min_height: 32
min_width: 32
model_path: checkpoints
name: pix2tex
num_layers: 4
num_tokens: 8000
optimizer: Adam
output_path: outputs
pad: false
pad_token: 0
patch_size: 16
sample_freq: 3000
save_freq: 5
scheduler: StepLR
seed: 42
temperature: 0.2
test_samples: 5
testbatchsize: 20
tokenizer: dataset/tokenizer.json
valbatches: 100
valdata: dataset/data/val.pkl

```

**Comment by TITC** [comment] 2022-05-15 02:14
How about now? @JaosonMa  one thing I want to mention is you can decrease the micro-batch size to increase `batchsize`.
such as
```YAML
batchsize: 64
micro_batchsize: 1
```
it may give you a more rapid speed to converge. The reason behind it is the accumulated gradient also occupies GPU memory.

**Comment by lukas-blecher** [comment] 2022-05-15 07:52
You should be able to increase the `batchsize` without changing `micro_batchsize`. While the gradient does occupy GPU memory it doesn't get bigger with a higher batch size.
So you should be able to say e.g.
```yaml
batchsize: 100
micro_batchsize: 10
```

**Comment by TITC** [comment] 2022-05-15 10:44
it's a blind area for me, I mistakenly believe gradient occupied memory will increase with batch size because I think if it won't increase, then the batch size can be infinite large in theoretical as long as the micro_batchsize does not overflow memory.

but I encountered `CUDA out of memory.` in micro_batchsize=1 and batchsize=500 with 4c94f3da2a41e8991378be19e8c8e7c56c478b51. How do you think about it? @lukas-blecher

**Comment by lukas-blecher** [comment] 2022-05-15 11:20
>  I think if it won't increase, then the batch size can be infinite large in theoretical as long as the micro_batchsize does not overflow memory.

I believe this is correct.

> but I encountered CUDA out of memory. in micro_batchsize=1 and batchsize=500

I don't understand this. I was not able to reproduce this. I can set a very large batchsize and during the micro batch iterations the used memory does not change. At which point did the error occur? Are you positive you were on the `micro-batch` branch?

**Comment by TITC** [comment] 2022-05-15 13:50
You are right, thanks for pointing out my mistake, otherwise I might keeping wrong all along.

I am in right branch but wrong conda environment at https://github.com/lukas-blecher/LaTeX-OCR/issues/147#issuecomment-1126906607. I have two env, one is [0.0.20](https://github.com/lukas-blecher/LaTeX-OCR/releases/tag/0.0.20) for some reason, named as `latex_ocr`. the other is created to reproduce this issue 2 days ago, named as `pix2tex_test`. 

> Sorry for late response, I pulled the latest code, create a clean conda env last night and do reproduce one time the abnormal bleu score.

I change the directory to the latest code folder but execute `python -m pix2tex.train --config model/settings/config.yaml` at `latex_ocr` env  so it call 0.0.20 version code, so out of memory. After change to the new conda env(`pix2tex_test`) the problem is gone.

For insurance, I also checked https://github.com/lukas-blecher/LaTeX-OCR/issues/147#issuecomment-1126611823 is in the new conda env. Each wandb execute has an id, this one is `3o033yr4`.
![image](https://user-images.githubusercontent.com/35098797/168476181-6dacede9-241a-4f6a-b5d8-eb9cdc2bc15f.png)


---

> Are you positive you were on the `micro-batch` branch?

yeah, sure. `git branch -a`
```shell
  main
* micro-batch
  remotes/origin/HEAD -> origin/main
  remotes/origin/appimage
  remotes/origin/gh-pages
  remotes/origin/main
  remotes/origin/micro-batch
```
`git rev-parse micro-batch` show 4c94f3da2a41e8991378be19e8c8e7c56c478b51
```shell
4c94f3da2a41e8991378be19e8c8e7c56c478b51
```

---
> At which point did the error occur?

[here](https://github.com/lukas-blecher/LaTeX-OCR/blob/e4b102ed30690c3b5488940193d12654cd91418f/pix2tex/models.py#L151)

**Comment by lukas-blecher** [comment] 2022-05-15 14:31
This section is there to prevent the user from trying out batch sizes that might not work for the largest images because of memory problems:

https://github.com/lukas-blecher/LaTeX-OCR/blob/4c94f3da2a41e8991378be19e8c8e7c56c478b51/pix2tex/models.py#L147-L155

So you probably are still somehow executing the previous version, where the entire batch size is tried out instead of the micro batch size (as it is the case in the snippet above). Your card won't be able to handle the 500 images at once, but in the new version the micro batch size is the deciding factor, so what you are telling me is that even a micro batch size of 1 would require more than the available memory (which is most likely not the case :))

I will need to add an error message by catching the "CUDA out of memory" error and explain what is happening.

I don't quite understand if you were able to solve the error.
> After change to the new conda env(pix2tex_test) the problem is gone.

Seems like it 👍 
So the only thing that remains to check is if @JaosonMa still has the problem.

**Comment by JaosonMa** [comment] 2022-05-16 00:54
sorry for later respose.  you two are awesome！

i train with the batchsize:40  ,micro_batchsize:10 , with config 100 epoce , Up to now, I don't think it's converging anymore
the result bleu highest is  0.79. There is still a big gap with your results
![image](https://user-images.githubusercontent.com/23551774/168502616-cdb966ba-0903-464c-998b-924168fee38e.png)

 i will try again with batchsize 80 or more,

**Comment by JaosonMa** [comment] 2022-05-16 02:37
> > I think if it won't increase, then the batch size can be infinite large in theoretical as long as the micro_batchsize does not overflow memory.
> 
> I believe this is correct.
> 
> > but I encountered CUDA out of memory. in micro_batchsize=1 and batchsize=500
> 
> I don't understand this. I was not able to reproduce this. I can set a very large batchsize and during the micro batch iterations the used memory does not change. At which point did the error occur? Are you positive you were on the `micro-batch` branch?

##########################
i changed batchsize from 80 - 60 - 50 with micro-batchsize 10 ,all of them error with CUDA out of memory. only 40 is good for me . so i watched the gpu memory changed .
this is batchsize 40 ,micro_batchsize 10 traind the first 100 step .
![train_40_10](https://user-images.githubusercontent.com/23551774/168509849-0b8982e6-ab39-4324-a9d4-6ca282089363.gif)

then i watched the gpu from the momert
![image](https://user-images.githubusercontent.com/23551774/168510461-d4d3df94-6e4d-45a1-ac7a-c6086c95a8ca.png)
![train_40_10-mid](https://user-images.githubusercontent.com/23551774/168510587-b21e75cf-3d35-46be-97c9-1af9616f5c22.gif)



the gpu memory line is almost like this : 
![image](https://user-images.githubusercontent.com/23551774/168510018-2cd71c8e-f83b-483f-b09e-5fe1c8981d81.png)

what i think is  after 100 step, GPU memory was settle in 5G。 but when the train start , the memory is  fluctuates greatly,but it is lower then 12G。that is why when i changed the batchsize high , The upper limit of fluctuation exceeds 12g，then error of cunda out of memory. 
this is what i think ,does  it make sense？ @lukas-blecher @TITC

**Comment by JaosonMa** [comment] 2022-05-16 02:47
Compared with the training of other colleagues, our GPU memory is very unstable, and the memory use in other stable training periods is almost a line. But our training fluctuates a lot

![train_40_10-mid2](https://user-images.githubusercontent.com/23551774/168511425-dd6c2036-8867-4c98-b726-0621bfbd379c.gif)

**Comment by TITC** [comment] 2022-05-16 03:24
Thanks for your explicit description of the GPU memory fluctuations phenomenon.

In fact, I have noticed it but describing it will need much time to reproduce and collect data. And control the GPU memory under the half of full will work fine based on experience. I was enlightened by this issue and have something to implement. Maybe the main reason is I am lazy.😂

here are some guesses and supplementary.

---

images are grouped by size when training, below debug screen shoot contains two groups `(128, 32)` and `(384,32)`. In the `(128, 32)` group, it's value is an python list, each element in it is a tuple`(normalized equation, relative image path)`. @JaosonMa 
 
![image_1649919164464_0](https://user-images.githubusercontent.com/35098797/168513232-257656af-179f-4532-a5d2-364253b65760.png)

`(128, 32)` represent a bunch of images high=32 and width=128, and `(384,32)` meaning same thing. So, if I am not wrong, I think that's the reason why memory fluctuations. Here are more informations from @lukas-blecher  at https://github.com/lukas-blecher/LaTeX-OCR/discussions/130#discussioncomment-2595391

>  The naive way to deal with this would be to pad all images to a fixed image size (here self.width x self.height). But then there would be much computation done without any meaning.

---

The other part is I am care about.
> i changed batchsize from 80 - 60 - 50 with micro-batchsize 10 ,all of them error with CUDA out of memory. only 40 is good for me . so i watched the gpu memory changed.  


based on previous comments https://github.com/lukas-blecher/LaTeX-OCR/issues/147#issuecomment-1126913617, it's kinda weird. And I do have some training record about `Out of memory` at the middle of epochs, not at the beginning. I do not understand why get over [max memory check](https://github.com/lukas-blecher/LaTeX-OCR/blob/4c94f3da2a41e8991378be19e8c8e7c56c478b51/pix2tex/models.py#L147-L155) but it still `out of memory`. @lukas-blecher 

![image](https://user-images.githubusercontent.com/35098797/168511804-69363dd4-07be-4cee-a526-4f18306b44a1.png)

**Comment by JaosonMa** [comment] 2022-05-16 10:14
here is my config
![image](https://user-images.githubusercontent.com/23551774/168569578-e07d7e53-c3f0-4772-9e57-899a5d5cfd3f.png)

this is  the gif

![train_40_10-mid2error](https://user-images.githubusercontent.com/23551774/168570698-0a52a36f-b37f-4f9e-aee7-e8dc25279d1a.gif)

**Comment by JaosonMa** [comment] 2022-05-16 10:32
this is batchsize:50 micro_batchsize:10  same error
![image](https://user-images.githubusercontent.com/23551774/168573830-01a5f331-b995-4351-b4a5-d91667df1f3f.png)

this is batchsize:40 micro_batchsize:10 it is good , i only changed the batchsize 
![image](https://user-images.githubusercontent.com/23551774/168574182-943d0ac8-0660-4b8a-a387-4ac4b5d116cd.png)

**Comment by lukas-blecher** [comment] 2022-05-16 10:47
![image](https://user-images.githubusercontent.com/55287601/168575927-c39198b1-512a-4c56-95b4-69b555199f72.png)
What I think is happening: Your script is calling the installed version of pix2tex (without the micro batching) and thus the script tries to run with a batchsize of 50 (which is too much for your system)
Why I think that? it says above the error happens in line 151 when calling `decoder(seq, context=encoder(im)).sum().backward()` but that Line in the micro batch branch comes later. However on the main branch it is exactly at 151:
https://github.com/lukas-blecher/LaTeX-OCR/blob/e4b102ed30690c3b5488940193d12654cd91418f/pix2tex/models.py#L151

please make sure your script `qqm_train.sh` calls the correct `train.py` file. Or better run 
`pip install -U --force -e .` in the micro batch dir

**Comment by JaosonMa** [comment] 2022-05-16 11:11
soga ,
first> pip uninstall pix2tex 
then go to the micro-batch > pip install .
changed the batchsize:80  ,now it no error ,

**Comment by JaosonMa** [comment] 2022-05-17 02:29
can i train without install pix2tex? i check train.py  
`from pix2tex.eval import evaluate
from pix2tex.models import get_model
from pix2tex.utils import *`
must install pix2tex then train .

**Comment by TITC** [comment] 2022-05-17 02:41
I make the same issue before https://github.com/lukas-blecher/LaTeX-OCR/issues/124#issue-1205237734 @JaosonMa 

---
yes, you can. package installed through pip is written code path to PYTHON_PATH, so you can import that package anywhere. It means you can do it manually.

```python
import sys
# # insert at 1, 0 is the script path (or '' in REPL)
sys.path.insert(1, 'path to the folder')
```
In this way, you do not need `pip install -e .` or `pip install pix2tex` but you need to add that part to each python file which needs to use pix2tex code.

**Comment by JaosonMa** [comment] 2022-05-17 02:43
> I make the same issue before [#124 (comment)](https://github.com/lukas-blecher/LaTeX-OCR/issues/124#issue-1205237734) @JaosonMa
> 
> yes, you can. package installed through pip is written code path to PYTHON_PATH, so you can import that package anywhere. It means you can do it manually.
> 
> ```python
> import sys
> # # insert at 1, 0 is the script path (or '' in REPL)
> sys.path.insert(1, 'path to the folder')
> ```
> 
> In this way, you do not need `pip install -e .` or `pip install pix2tex` but you need to add that part to each python file which needs to use pix2tex code.

i tried another way ,i copy the train.py to the Latex-OCR . then can train without install, but i don't sure is this way all right.

**Comment by TITC** [comment] 2022-05-17 02:56
> but i don't sure is this way all right.

so am I. If you are positive that pix2tex is not installed in your env and the model converges some time later, I think it's right. Basically, it's a question of whether the python interpreter can find the code.

```
---train.py
   |___pix2tex
```
I do know there has one situation it works, such as if your workspace is `LaTex-OCR` and you execute train.py then it's a relative import.

**Comment by JaosonMa** [comment] 2022-05-17 03:02
> 

it look something was wrong ,because after one epco ,ther is no bleu socre  show up .
![image](https://user-images.githubusercontent.com/23551774/168719663-2f3717c3-2918-4be5-81fc-81c27fdeb0f1.png)

**Comment by TITC** [comment] 2022-05-17 03:05
> it look something was wrong ,because after one epco ,ther is no bleu socre show up .

what's the value of your `sample_freq`, it means how many steps to evaluate bleu. Steps showed in your screen shot is 2023+203 is less than 3000 shared in https://github.com/lukas-blecher/LaTeX-OCR/issues/147#issuecomment-1127483997

**Comment by JaosonMa** [comment] 2022-05-17 03:10
`what's the value of your sample_freq, it means how many steps to evaluate bleu.`   i got . i will try retrain once .

**Comment by TITC** [comment] 2022-05-17 06:26
The issue is around poor training results, but I think there are some unrelated things mixed up in it, such as memory fluctuations, and python path. It could be better to discuss them in [the discussion part](https://github.com/lukas-blecher/LaTeX-OCR/discussions). 

And you have achieved bleu 0.855 at https://github.com/lukas-blecher/LaTeX-OCR/issues/147#issuecomment-1128358876, if there haven't any further questions about it, I think it is better to close this issue.

**Closed** 2022-05-17 06:31 UTC
Labels: training

**Comment by JaosonMa** [comment] 2022-05-30 01:25
i come back again.
last week i finally create my own data , it was all the 1 channels gray imgs,  i also  create my own tokenizer.json，
then i use then to train , with the sall config just channged the train.val&val.pkl path& json path.
but got an error 

![image](https://user-images.githubusercontent.com/23551774/170901092-3ab44814-44fe-49ae-9744-0e75013b9fa4.png)

please give me some help .

**Comment by lukas-blecher** [comment] 2022-05-30 08:24
see #101
