### ISSUE TITLE
2 issues found in `LaTeX-OCR training.ipynb`

### ISSUE THREAD

**Issue by TITC** [lukas-blecher/LaTeX-OCR#116] opened 2022-04-04 15:15 UTC
1. failure to obtain files in line 5-6

<img src="https://user-images.githubusercontent.com/35098797/161573482-dea5a4a9-c1ba-475e-a960-d921bef7eab8.png" width="550">

and I found a solution at [stackoverflow](https://stackoverflow.com/a/71176719/11430711)

```shell
!pip install --upgrade --no-cache-dir gdown
```

2. `!python train.py --config settings/colab.yaml` report below RuntimeError.

```shell
wandb: Currently logged in as: tyh (use `wandb login --relogin` to force relogin)
wandb: Tracking run with wandb version 0.12.11
wandb: Run data is saved locally in /content/LaTeX-OCR/wandb/run-20220404_145442-3vapz5i7
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run mixed
wandb: ⭐️ View project at https://wandb.ai/tyh/LaTeX-OCR
wandb: 🚀 View run at https://wandb.ai/tyh/LaTeX-OCR/runs/3vapz5i7
Traceback (most recent call last):
  File "train.py", line 88, in <module>
    train(args)
  File "train.py", line 29, in train
    model = get_model(args, training=True)
  File "/content/LaTeX-OCR/models.py", line 149, in get_model
    decoder(seq, context=encoder(im)).sum().backward()
  File "/usr/local/lib/python3.7/dist-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb:                                                                                
wandb: Synced mixed: https://wandb.ai/tyh/LaTeX-OCR/runs/3vapz5i7
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20220404_145442-3vapz5i7/logs
```

**Comment by lukas-blecher** [comment] 2022-04-04 17:02
Ok thanks. I added the first line.
I don't know why the second error arises though.
almost as if there was the `torch.no_grad` flag set.
Anyway, I've noticed the code that is throwing the error is not even working as intended. I might remove it all together.

**Comment by TITC** [comment] 2022-04-05 00:13
the same error even `Restart runtime` after add that line.

```python
Traceback (most recent call last):
  File "train.py", line 88, in <module>
    train(args)
  File "train.py", line 29, in train
    model = get_model(args, training=True)
  File "/content/LaTeX-OCR/models.py", line 150, in get_model
    decoder(seq, context=encoder(im)).sum().backward()
  File "/usr/local/lib/python3.7/dist-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

![image](https://user-images.githubusercontent.com/35098797/161653528-9cda3c14-9fc3-4a14-9fef-f7851c05e936.png)

**Comment by lukas-blecher** [comment] 2022-04-05 16:42
Ok, I think I will remove this code. It's not working as intended anyway

**Comment by Astro-Lee** [comment] 2022-04-07 05:05
Hi，@TITC.  Is this problem solved?

**Comment by TITC** [comment] 2022-04-07 05:45
Nope @Astro-Lee

**Comment by TITC** [comment] 2022-04-07 06:59
And I found another problem, [this line](https://github.com/lukas-blecher/LaTeX-OCR/blob/08053ab63d79a475c747cfc8d74c017166d1295a/eval.py#L56) `encoded = model.encoder(im.to(device))` will cause error when I predict on [handwritten dataset](https://drive.google.com/uc?id=13vjxGYrFCuYnwgDIUqkxsNGKk__D_sOM) (provide by author).

the error is dimension does not match.

But I haven't time to reproduce it, so just leave a message.

**Comment by lukas-blecher** [comment] 2022-04-08 13:37
I made a stupid mistake in a previous commit. Should be fixed now-

**Closed** 2022-04-08 13:36 UTC
